### ISSUE TITLE
Create new feature

### ISSUE THREAD

**Issue by rvrtester** [mapbender/mapbender-digitizer#14]
After you create a new feature in Mapbender (per digitizer) a form to fill in the attributes will show up directly. If you click on "Cancel" on this form a feature (without any attributes) will remain.

The button "Cancel" should abort the action without a rest.

**Comment by AxxL** [comment]
We will discuss the workflow behind that. Right now geometries are directly put into the database and attributes coming right after.

**Comment by rvrtester** [comment]
An input for your discussion:

A new option to digitizer Element like:

 * openDialogAfterElemetCreated

OR

 * saveFeatureAfterElementCreated

could be a solution...

**Comment by AxxL** [comment]
@rvrtester 

> openDialogAfterElemetCreated
> saveFeatureAfterElementCreated

"openFormAfterEdit" is a parameter that opens the dialog after creating a geometry. It doesn't work yet for moving or editing geometries.

The only workaround right now is to open the attribute dialog right now to save after an edit of geometry or attributes.

I've created a new ticket at #17 and will close this ticket if you don't have another question.
