### ISSUE TITLE
Show only features inside the map window

### ISSUE THREAD

**Issue by rvrtester** [mapbender/mapbender-digitizer#16]
The function "Show only features inside the map window" (checkbox) in Mapbender is erroneous.

_Example:_

1. Start application
2. Start digitizer
3. Zoom in (only features inside the map window were shown)
4. Uncheck the checkbox (all features were shown in the left pane)
5. Check the checkbox (only features inside the map window were shown)
6. Uncheck the checkbox (only features inside the map window were shown in the left pane - **which is wrong!**)

**Comment by AxxL** [comment]
Confirmed in Digitizer 1.0: http://release.mapbender3.org/application/mapbender_digitize_demo

- Point Digitizing.
- Zoom in
- Check checkbox.
- Table doesn't react no more.

**Comment by eSlider** [comment]
@AxxL, please check again. This should be fixed.

**Comment by AxxL** [comment]
See: http://release.mapbender3.org/application/mapbender_digitize_demo
1.0.48. Fixed.
