### ISSUE TITLE
Workflow for saving geometries

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender-digitizer#17]
Create a workflow for saving geometries without the attribute dialogue.

Right now you have to manually open the attribute dialog to save your edit. 

Several possibilities:

1.) Add a save button into the toolbar of the digitizer. The save button needs to be clicked after editing a geometry. The save button gets in an "active state", after a change was made and in an "inactive" state when no change was made.

2.) Save option in the context-menu: Add a save option in the context menu, that you have to click manually after editing the geometry.

3.) Event "openForamAfterEdit": Change the event that it also listens if you change a geometry. It listens right now only if you created one.

**Comment by rvrtester** [comment]
4.) Another possibility could be:

- Saving any type of geometry (in the database) right now after every change (creating, moving,...)
- Append or edit attributes via the attribute dialogue (as a separate and stand-alone action)
- A parameter _openFormAfterEdit_ that opens the dialog after creating, moving... a geometry (for comfort)

**Comment by astroidex** [comment]
old ticket. I close it.
