### ISSUE TITLE
The formatting of a date seems not to work

### ISSUE THREAD

**Issue by rvrtester** [mapbender/mapbender-digitizer#18]
Example:

A date-field (with a datepicker) has the **_type: date_** and the **_format: YYYY-MM-DD_** (YAML-Defintion). But the datepicker displays the current day as 05.01.2017 (and not as 2017-01-05). The database stores the current day also as 05.01.2017. So the **_format: YYYY-MM-DD_** has no effect.

(Furthermore it is possible to overwrite values of the datepicker. You can edit a value like _05.01.2017_ to a value like _05....01....201789_. But under https://jqueryui.com/datepicker/ it is also possible to overwrite values of the datepicker in this way)

**Comment by astroidex** [comment]
Sorry. Definition changed. 

Please define the dateformat with **dateFormat**  instead of **format** to get something like 2017-01-05:

```
                -
                  type: date
                  title: 'Antrag vom'
                  name: antrag
                  css: { width: 50% }
                  dateFormat: yy-mm-dd
```

We will fist this in the documentation soon.
