### ISSUE TITLE
Delete points of a line

### ISSUE THREAD

**Issue by rvrtester** [mapbender/mapbender-digitizer#20]
It is possible to digitize a line and move the points of this line to another location.

Is it possible to delete one point (or more points) of a line?
If not - this would be a helpful feature.

**Comment by ruhri** [comment]
Also splitting a line/polygon into two parts would be a very useful tool (ofcourse inheriting the attributes of the parent-object...)

**Comment by eSlider** [comment]
@rvrtester, yes removing is posible, but only if you right click on the map, then select one point and uses "del" key. Strange behaviour, but we look how to fix this and make more usable.

**Comment by eSlider** [comment]
@ruhri, thank you for the suggesting. Can you please explain the workflow to doing this?

**Comment by rvrtester** [comment]
@eSlider 

Thank you for the solution! It worked for me!

1) Press the button _Select and edit geometry position/size_
2) Select on line &rarr; Points become visible
3) Move the cursor (which is now a cross-hair) exactly over the point to delete
4) Do one right-click with the mouse
5) Press the DEL-Key
6) Save the feature

**Comment by ruhri** [comment]
Splitting of Features could look like this, maybe too complicated?:
1. Select a Feature (Line or Polygon)
2. draw a line which, splits the selected feature into two parts (then the old feature doesn't exist anymore)
3. the origin features attributes should be inherited from to both new resulting features

compare to QGIS "split features"-Tool in "advanced digitizing toolbar".

Please also have look at this:
http://docs.openlayers.org/library/controls/split.html
http://dev.openlayers.org/examples/split-feature.html

**Comment by eSlider** [comment]
@ruhri, yes it's posible. Thank you for your suggestion. 
But this is offtopic of the context, please make new issue for that.
