### ISSUE TITLE
Checkbox values true/false/NULL

### ISSUE THREAD

**Issue by rvrtester** [mapbender/mapbender-digitizer#22]
The digitizer provides the definition of checkboxes as a form element.

If the checkbox is checked by the user, the value _**true**_ will be saved in the database.

If the checkbox is unchecked by the user, the value _**NULL**_ will be saved in the database.
In my opinion the value _**false**_ is correct not the value _**NULL**_.

Furthermore this behavior could cause problems, if the column in the database is defined as _**NOT NULL**_.

**Comment by eSlider** [comment]
@rvrtester, Indeed, and in some cases there is need to save 1/0 and so one. 
Furthermore sometimes you need to save essential information like creation date or user id. 
For this cases you can define pre and post save events:
```yaml
featureType:
  connection: connectionName
  table: schema.tableName
  uniqueId: id
  geomType: multipolygon
  geomField: geom
  srid: 31466
  events:
  
    # PHP code evalution before save feature data
    onBeforeSave: |
    
       // Get feature attributes as array
       $attributes = $feature->getAttributes();
       
       // Checkbox value check
       if($attributes["fieldName"] == null){
          $attributes["fieldName"] = false;
       }
       
       // Check if user is logged 
       if($user){
          $attributes["fieldName"] = $user->getId(); 
       }
       
       // Set feature attributes
       $feature->setAttributes($attributes);
```
