### ISSUE TITLE
Use of concatenation and the type "text"

### ISSUE THREAD

**Issue by rvrtester** [mapbender/mapbender-digitizer#35]
If you use the type "text" in a form, it stands out that...

...this works perfect:

```
- type: text
  title: Name
  name: name
  css: {width: 80%}
  text: data.name
```

...this does not work:

```
- type: text
  title: Name
  name: name
  css: {width: 80%}
  text: 'The name is ' + data.name

```
The problem is the concatenation with the symbol "+"...

You can save the first version, but you cannot save the second.
It is not possible to save the YAML configuration if it contains the symbol "+".

Example taken from: https://doc.mapbender3.org/de/bundles/Mapbender/CoreBundle/elements/digitizer.html#texte-type-text

**Comment by AxxL** [comment]
Confirmed.

One step further: If text start wirth a label it can be saved but isn't displayed.

```
text: 'The name is '
```

**Comment by eSlider** [comment]
@rvrtester, please try

```yaml
text: "'The name is ' + data.name"
```
or

```yaml
text: |
  'The name is ' + data.name
```

**Comment by rvrtester** [comment]
Yes, this solution works.

However, the second version (with the pipe) will be converted by the Mapbender Editor to:

`text: "'The name is ' + data.name\n"`
