### ISSUE TITLE
Date field with NULL values

### ISSUE THREAD

**Issue by rvrtester** [mapbender/mapbender-digitizer#36]
If you have a table with a column of type "date", and one or more values in this column are NULL - these NULL values will be displayed as "01.01.1970" (Start of Unix time) in the Mapbender3 Application (which is wrong).

**Comment by eSlider** [comment]
@rvrtester, what do you expect to set?

**Comment by astroidex** [comment]
I had the same experience. The default for a NULL value is "01.01.1970" at the moment. How to configure this?

**Comment by AxxL** [comment]
Checked into board.

**Comment by CharlyUnicorn** [comment]
i had the same experience : )

**Comment by astroidex** [comment]
Date field now supports NULL values.
