### ISSUE TITLE
Type breakline

### ISSUE THREAD

**Issue by rvrtester** [mapbender/mapbender-digitizer#37]
The type _breakline_ seems not to work...

If you use this type, the application doesn't insert a simple line but the string _{"type":"breakline"}_ instead.

**Comment by eSlider** [comment]
@rvrtester, type's wording is case sensetiv. 
Here an example of how it is correct to write: 
```json
 {"type":"breakLine"}
```

**Comment by rvrtester** [comment]
Thank you!

I have copied and pasted the example from the documentation, where it is written in small letters:
https://doc.mapbender3.org/de/bundles/Mapbender/CoreBundle/elements/digitizer.html#trennlinien-type-breakline

**Comment by astroidex** [comment]
Hi. I fixed the documentation and created 2 pull requests for the documentation.
https://github.com/mapbender/mapbender-documentation/pull/22
https://github.com/mapbender/mapbender-documentation/pull/23
